#!/usr/bin/env bash

# this file exists because CentOS 7 has too old git version and cannot run the following pipeline
#
# test -e ${tarball_manifest_path} || git ls-files --recurse-submodules | grep --invert-match --file=${tarball_exclude_path} > ${tarball_manifest_path}

PROJECT_ROOT="$( cd "$(dirname "$0"/..)" >/dev/null 2>&1 ; pwd -P )"

tarball_manifest_path="$1"
tarball_exclude_path="$2"
if [ ! -e "$tarball_manifest_path" ]
then
    git ls-files | grep --invert-match --file="${tarball_exclude_path}" > "${tarball_manifest_path}"
    for repo in $(git submodule foreach --quiet "realpath --relative-base=${PROJECT_ROOT} \$(pwd)")
    do
        (
            cd "${PROJECT_ROOT}/${repo}"
            git ls-files | sed "s:^:${repo}/:" | grep --invert-match --file="${tarball_exclude_path}" >> "${tarball_manifest_path}"
        )
    done
fi
